name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go